config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    #resources :secrets, :only => [:new]
    resources :friendships, :only => [:create]
    resources :secrets, :only => [:create]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :friendships, :only => [:destroy]

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validates :origin, :target, presence: true
  validates_uniqueness_of :target, :scope => :origin

  belongs_to :origin, :class_name => "User"
  belongs_to :target, :class_name => "User"

  def self.can_friend?(origin_id, target_id)
    (origin_id != target_id) &&
      (!Friendship.exists?(origin_id: origin_id, target_id: target_id))
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  validates :author_id, :recipient_id, :title, :presence => true

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings,  inverse_of: :secret
  has_many :tags, :through => :secret_taggings
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  validates :secret, :tag, :presence => true
  validates :secret, :uniqueness => { :scope => :tag }

  belongs_to :secret, inverse_of: :secret_taggings
  belongs_to :tag, inverse_of: :secret_taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :title, :presence => true, :uniqueness => true

  has_many :secret_taggings,  inverse_of: :tag
  has_many :secrets, :through => :secret_taggings
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  has_many :owned_friendships,
      :foreign_key => :origin_id,
      :class_name => "Friendship",
      :inverse_of => :origin
  has_many :incoming_friendships,
      :foreign_key => :target_id,
      :class_name => "Friendship",
      :inverse_of => :target

  has_many :friends, through: :owned_friendships, source: :target
  has_many :admirers, through: :incoming_friendships, source: :origin

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_current_user!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url unless signed_in?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.new
    @friendship.origin_id = current_user.id
    @friendship.target_id = params[:user_id]
    @friendship.save!
    render :json => @friendship, status: 200
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    if @friendship.nil?
      puts params
      head 404
    else
      @friendship.destroy!
      head 200
    end
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new
    @secret.author_id = current_user.id
    @secret.recipient_id = params[:user_id]
    render :new
  end

  def create
    @secret = Secret.new(secret_params)
    @secret.author_id = current_user.id
    @secret.recipient_id = params[:user_id]
    if @secret.save
      results = [@secret, @secret.tags]
      render :json => results, :status => 200
    else
      render :json => @secret.errors.full_messages, :status => 422
    end
  end

  private
  def secret_params
    params.require(:secret).permit(:title, :tag_ids => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.sign_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:index, :show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
    @friendships = current_user.owned_friendships
    render :index
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    @secret = Secret.new
    if !params.include?(:id)
      redirect_to user_url(current_user)
      return
    end

    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def csrf_token
    "<input
       name='authenticity_token'
       type='hidden'
       value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
      <%= error %>
      <br>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= render "layouts/errors"%>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<script id="tags_list" type="application/json">
  { "tags" : <%= Tag.all.to_json.html_safe %>     }
</script>

<script id="tags_template" type="text/template">
  <select name="secret[tag_ids][]" id="tags">
  <%% _(tags).each( function(tag) { %>
    <option value='<%%= tag.id %>'><%%= tag.title %></option>
  <%% }); %>

  </select>
</script>

<script>
  $(document).ready(function(){
    var addTagSelector = function() {
      var tags = JSON.parse($('#tags_list').html())['tags'];
      var templateCode = $('#tags_template').html()
      var tagsTemplateFn = _.template(templateCode);
      return tagsTemplateFn( {
        tags: tags
      });
    };

    $('#add-tag').on('click', function(event) {
      event.preventDefault();
      var renderedContent = addTagSelector();
      $('#tags-container').append(renderedContent);
    })
  });


</script>

<form action="<%= user_secrets_url(params[:id]) %>"
  method="POST" id="secret-form">
  <%= csrf_token %>

  <label>Title
  <input type="textarea" name="secret[title]" value="<%= @secret.title %>" id="new-secret-title">
  </label>

  <div id="tags-container"><label for="tags">Tags</label>
  <a id="add-tag" href="#">Add Tag</a>
  </div>

  <input type="submit" value="Send Whisper" id="add-secret">
</form>

app/views/secrets/new.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<ul id="users">
<% @users.each do |user| %>
  <li><%= user.username %></li>
  <div class="friend-buttons <%=
    @friendships.any? { | fs| fs.target_id == user.id } ?
      'can-unfriend' :
      ( current_user.id == user.id ? '' : 'can-friend' ) %>">
    <button class="friend" data-id="<%= user.id %>">Friend </button>
    <button class="unfriend"
      data-id="<%= friendship = @friendships.find do |fs|
        fs.target_id == user.id
      end
      friendship.id if friendship %>">Unfriend </button>
  </div>
<% end %>
</ul>

<script type="application/javascript">
  $('#users').on('click', '.friend', function(event) {
    $.ajax({
      url: "/users/" + $(event.target).data("id") + "/friendships/",
      type: "POST",
      success: function(friendship) {
        console.log(friendship);
        $(event.target).parent().toggleClass("can-friend can-unfriend");
        $(event.target).removeAttr("disabled");
        $(event.target).text("Friend");
        $($(event.target).siblings()[0]).data("id", friendship['id'])
      }
      ,
      error: function() {
        alert("FAIL");
        $(event.target).removeAttr("disabled");
        $(event.target).text("Friend");
      }
    })
    $(event.target).text("Friending...");
    $(event.target).attr("disabled", "true");
  })

  $('#users').on('click', '.unfriend', function(event) {
    $.ajax({
      url: "/friendships/" + $(event.target).data("id"),
      type: "DELETE",
      success: function() {
        $(event.target).parent().toggleClass("can-friend can-unfriend");
        $(event.target).removeAttr("disabled");
        $(event.target).text("Unfriend");
      },
      error: function() {
        alert("FAIL");
        $(event.target).removeAttr("disabled");
        $(event.target).text("Unfriend");
      }
    })
    $(event.target).text("Unfriending...");
    $(event.target).attr("disabled", "true");
  })


</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<h3>Add a Secret!</h3>
<%= render 'secrets/form' %>
<br><br>
<ul id="secrets-list">
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
      <ul id="secret-<%= secret.id %>-tags-list">
        <% secret.tags.each do |tag|  %>
          <li> <%= tag.title %> </li>
        <% end %>
      </ul>
  <% end %>
</ul>

<script>

  $('#add-secret').on('click', function(event) {
    event.preventDefault();
    $.ajax({
      url: "/users/<%= @user.id %>/secrets",
      type: "POST",
      data: $("#secret-form").serializeJSON(),
      success: function(results){
        var secret = results[0];
        var tags = results[1];
        $('#secrets-list').prepend("<li>"+ secret.title + "</li>"
          +"<ul id='secret-" + secret.id + "-tags-list'></ul>"
        );

        tags.forEach(function(tag) {
          $('#secret-' + secret.id + '-tags-list').append(
            $('<li>' + tag.title + '</li>'));
        });

        $('#new-secret-title').val("");
        $("#tags-container").empty();
      },
      error: function(errors){
        alert(errors.responseText);
      }
    })
  })
</script>